### ISSUE TITLE
First step and usage in flutter App

### ISSUE THREAD

**Issue by kekko7072** [ngngardner/dart_ipfs_client#3]
Hey @ngngardner,
I just discovered the Web3 and IPFS thing and I really like it. I am trying to develop an simple app to store short message  in other user phone storage, based on flutter and I have some question.
1) It's ready to use it on Flutter?
2) Can i use other user phone storage to create the storage network of the message?
3) I can access the message searching for the HASH directly to the network, right?
4)I will need a place (as a server ) to storage all the available hash elements or I can use other ways to make the network "discoverable"?

Thank you so much I really appreciate your first step into this IPFS thing. 

Best Regard
Francesco

**Comment by ngngardner** [comment]
Hi @kekko7072, your project sounds like a great idea.

1. This project simply implements two methods of the IPFS HTTP API, `cat` and `add`. It should be usable with flutter, although maybe not with the newest versions due to null-safety requirements.
2. I don't believe this is possible since there is not an IPFS node application for mobile yet (AFAIK). You will likely need to use a remote IPFS server.
3. Yes, you can access the message as long as you have the hash and can make request to an IPFS node.
4. You will need some way to associate the messages with the hash.  A server would be the most straight-forward way. I am unsure if other methods exist but they may. 

Best of luck.

**Comment by kekko7072** [comment]
@ngngardner thank you for the explanation, now I will search more info about IPFS and try to create my network. Can you add null safety to the plugin? Fell free to suggest me any docs or video I start from scratch on this so I will try to learn as much as I can.

**Comment by ngngardner** [comment]
I may in the future. For now, there is a fork of this repo that seems to have null safety implemented.
